### ISSUE TITLE
Chart does not show - Failed to execute 'arc' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by danada** [carlcraig/tc-angular-chartjs#9] opened 2014-09-30 01:08 UTC
If the dataset is changed on a doughnut chart with the `responsive` option set to **true**, an `Uncaught IndexSizeError` occurs when the container is resized (when resize() is called in Chart.js).

There is an issue open on the Chart.js repo: https://github.com/nnnick/Chart.js/issues/592

However, the issue above states the problem happens upon resizing the initial chart. I am not experiencing the issue on the initial draw, but on subsequent chart creations. Should be able to post a sample soon, just wondering if there are any obvious answers before I get too deep into this one.

**Comment by liammccann1992** [comment] 2015-02-28 18:30
I am experiencing this problem as well.

It's as simple as if you have a PIE chart and Doughnut chart and one is hidden.

The error is reproduced by doing the following:
- Load page with one of the two graph shown
- Change data that the graphs so
- Hide currently shown graph so other graph and it breaks

This error is also displayed every time the data is changed and one graph is hidden

**Comment by liammccann1992** [comment] 2015-02-28 18:36
Uncaught IndexSizeError:
 Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative.Chart.js:1206
 Chart.Arc.Chart.Element.extend.drawChart.js:2477 (anonymous function)
Chart.js:181 helpers.eachChart.js:2468 
Chart.Type.extend.drawChart.js:678 helpers.animationLoop.animationFrame

**Comment by liammccann1992** [comment] 2015-02-28 18:41
Confirmed "ng-if" rather "ng-show"/"ng-hide" solves this issue and logically makes a lot of sense.

**Comment by rafialikhan** [comment] 2015-03-05 22:07
I am getting a similar erorr Uncaught IndexSizeError in my angular implementation, the chart renders but still gives this error. 

Chart.min.js:10 Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative. Also when the charts are hidden and then loaded, it doesn't render at all.

But when i try to replicate the same, I am unable to do so here in jsfiddle.  
I have 3 cases, 1 is ng-if, 2 is ng-show and 3rd is ng-include and everything works fine however chart only animates on ng-if and not the others.

Maybe this helps someone figure out a solution. 
http://jsfiddle.net/o9ty4L62/

Reference Code - http://jsbin.com/ponumajuvo/1/edit

**Comment by mika76** [comment] 2015-03-11 14:43
Also noticed this in bootstrap tab control

**Comment by nishthanuj** [comment] 2015-03-19 12:17
Facing the same error while using chart.js with ionic framework. Is any one get the solution or any type of hack?

**Comment by carlcraig** [comment] 2015-03-19 12:49
Try putting the chart in a `ng-if` where it is only shown when the tab is visible.

**Comment by rafialikhan** [comment] 2015-03-31 19:29
Thanks carlcraig - even though i didnt have tabs i still went ahead and used ng-if to show the charts only if data is loaded and ng-if worked - will test it in a few more scenarios and report back.

**Comment by BastiaanAndriessen** [comment] 2015-05-05 14:45
Hi, I get the same error even though all my DOM elements are rendered and the data is available before I use the Chart.js functions. Any idea how I could solve this?

**Comment by DONSA** [comment] 2015-05-15 18:38
I have the same problem using Visual Composer (that uses Bootstrap) on Wordpress.

**Comment by galcivar** [comment] 2015-05-25 02:27
@rafialikhan how did you go about it? I don't use tabs either and I am struggling to determine if data is loaded as the chart is loaded only once and only happens when I navigate through the menu.

**Comment by krnlde** [comment] 2015-05-29 08:51
If have the same issue here. It even throws when the site containing the chart isn't even active. The thing is I can't reproduce it deterministically, so I guess it's some kind of race condition. Sorry I can't provide a solution for now.

**Comment by JonahTurnquist** [comment] 2015-08-09 09:04
I have the same issue when resizing a reactive pie chart

Options:
			responsive: true,
			maintainAspectRatio: false

**Comment by DanielMSchmidt** [comment] 2015-09-18 12:02
same issue here, +1

**Comment by RWOverdijk** [comment] 2015-12-18 22:19
:+1: ..

**Comment by AlaaSelim** [comment] 2016-01-07 05:26
same issue here, +1

**Comment by jailandrade** [comment] 2016-01-11 16:46
I don't know if it is the same issue but the chart doesn't show until I hover.

**Comment by didadan** [comment] 2016-03-04 00:21
We use a modal. With Chart.js Version 1.0.1 included it works on normal templates. When included in a modal the error in this issues title shows up. Charts don't show up at all until I hover when we use 1.0.2 like @jailandrade said. That hover issue we have since tc-angular-chartjs after version 1.0.9 or so.

**Comment by didadan** [comment] 2016-03-04 18:50
Our solution was as @mbyrne00 wrote: **Change the ng-show to ng-if**. The modal wasn't the problem but a parent element which had the ng-show attribute. Also downloaded Chart.js 1.0.2 today and the 'Chart just shows on hover' problem is gone. @jailandrade you should try it now.

**Comment by carlcraig** [comment] 2016-09-04 02:59
I am going to close this.
I cannot replicate this in the new `2.X` version which is using Chart.js `2.X`

Please re-open if the issue still happens in 2.x.

**Closed by carlcraig** 2016-09-04 02:59 UTC
Labels: bug

**Comment by eighteen14k** [comment] 2017-04-13 13:52
I'm seeing this error with 3.3.1 whilst attempt to build gauges (to show disk space used):

"Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-2.4) is negative.

**Comment by eighteen14k** [comment] 2017-04-13 14:09
But then with Chrome 57, I see a *lot* of errors with "SingleStat" when using the gauge.
